
;; Library files to be included.
$include "sfupmac.lib"
;; Library files to be included.
$include "sfupblin.lib"
;; End of include file list.
;;dynamic symbols allocated for this BLOCK
___RegDyn_C000001___SG_COB_0		EQU		R [1]		;	Define 1 registers for dynamic usage.
___FlgDyn_C000001___SG_COB_0		EQU		F [1]		;	Define 1 registers for dynamic usage.
;;end of dynamic symbols allocated for this BLOCK

;;Start Static symbols allocated for this BLOCK
__stc_id_00001_var_00___SG_COB_0       EQU     T                    ;static variable Tim[1]
__stc_id_00001_var_01___SG_COB_0       EQU     F                    ;static variable Sta[1]
;;End Static symbols allocated for this BLOCK
;;Start Dynamic symbol aliases allocated for this BLOCK
__fup_C000001_00_26_12___SG_COB_0       EQU                        ___FlgDyn_C000001___SG_COB_0+0 ;Export name of network.
;;End Dynamic symbol aliases allocated for this BLOCK
